"""Agregar columna direccion a cliente

Revision ID: 0bf9179c1928
Revises: 545d03c8b89e
Create Date: 2026-03-03 18:52:37.113989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0bf9179c1928"
down_revision: Union[str, None] = "545d03c8b89e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cita_vacunacion", "fecha_aplicacion")
    op.drop_column("cita_vacunacion", "proxima_dosis")
    op.drop_column("cita_vacunacion", "aplicada")
    op.add_column("cliente", sa.Column("direccion", sa.String(), nullable=True))
    op.drop_column("vacuna", "descripcion")
    op.drop_column("vacuna", "intervalo_dias")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacuna",
        sa.Column("intervalo_dias", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "vacuna",
        sa.Column("descripcion", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("cliente", "direccion")
    op.add_column(
        "cita_vacunacion",
        sa.Column("aplicada", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "cita_vacunacion",
        sa.Column(
            "proxima_dosis", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "cita_vacunacion",
        sa.Column(
            "fecha_aplicacion",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
