"""Crear todas las tablas

Revision ID: 180e372b4301
Revises: 
Create Date: 2026-02-28 13:17:31.054353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180e372b4301'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('vacunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fabricante', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacunas_id'), 'vacunas', ['id'], unique=False)
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=True),
    sa.Column('raza', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mascotas_id'), 'mascotas', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('veterinario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinario_id'), 'veterinario', ['id'], unique=False)
    op.create_table('citas_vacunacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=True),
    sa.Column('vacuna_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['vacuna_id'], ['vacunas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_vacunacion_id'), 'citas_vacunacion', ['id'], unique=False)
    op.drop_index('ix_sedes_id', table_name='sedes')
    op.drop_table('sedes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sedes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sedes_pkey')
    )
    op.create_index('ix_sedes_id', 'sedes', ['id'], unique=False)
    op.drop_index(op.f('ix_citas_vacunacion_id'), table_name='citas_vacunacion')
    op.drop_table('citas_vacunacion')
    op.drop_index(op.f('ix_veterinario_id'), table_name='veterinario')
    op.drop_table('veterinario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_mascotas_id'), table_name='mascotas')
    op.drop_table('mascotas')
    op.drop_index(op.f('ix_vacunas_id'), table_name='vacunas')
    op.drop_table('vacunas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
