"""Crear todas las tablas

Revision ID: 7c007df5029b
Revises: 180e372b4301
Create Date: 2026-03-01 00:16:46.773601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7c007df5029b"
down_revision: Union[str, None] = "180e372b4301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cliente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("telefono", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_cliente_id"), "cliente", ["id"], unique=False)
    op.create_table(
        "sede",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("direccion", sa.String(), nullable=False),
        sa.Column("telefono", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sede_id"), "sede", ["id"], unique=False)
    op.create_table(
        "vacuna",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("fabricante", sa.String(), nullable=True),
        sa.Column("dosis_requeridas", sa.Integer(), nullable=False),
        sa.Column("intervalo_dias", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacuna_id"), "vacuna", ["id"], unique=False)
    op.create_table(
        "mascota",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("especie", sa.String(), nullable=True),
        sa.Column("raza", sa.String(), nullable=True),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mascota_id"), "mascota", ["id"], unique=False)
    op.create_table(
        "veterinario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("especialidad", sa.String(), nullable=True),
        sa.Column("sede_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sede_id"],
            ["sede.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_veterinario_id"), "veterinario", ["id"], unique=False)
    op.create_table(
        "cita_vacunacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("aplicada", sa.Boolean(), nullable=True),
        sa.Column("fecha_aplicacion", sa.DateTime(), nullable=True),
        sa.Column("proxima_dosis", sa.DateTime(), nullable=True),
        sa.Column("mascota_id", sa.Integer(), nullable=False),
        sa.Column("vacuna_id", sa.Integer(), nullable=False),
        sa.Column("veterinario_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mascota_id"],
            ["mascota.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vacuna_id"],
            ["vacuna.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veterinario_id"],
            ["veterinario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cita_vacunacion_id"), "cita_vacunacion", ["id"], unique=False
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("rol", sa.String(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=True),
        sa.Column("veterinario_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veterinario_id"],
            ["veterinario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_usuario_id"), "usuario", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usuario_id"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_index(op.f("ix_cita_vacunacion_id"), table_name="cita_vacunacion")
    op.drop_table("cita_vacunacion")
    op.drop_index(op.f("ix_veterinario_id"), table_name="veterinario")
    op.drop_table("veterinario")
    op.drop_index(op.f("ix_mascota_id"), table_name="mascota")
    op.drop_table("mascota")
    op.drop_index(op.f("ix_vacuna_id"), table_name="vacuna")
    op.drop_table("vacuna")
    op.drop_index(op.f("ix_sede_id"), table_name="sede")
    op.drop_table("sede")
    op.drop_index(op.f("ix_cliente_id"), table_name="cliente")
    op.drop_table("cliente")
    # ### end Alembic commands ###
